### ISSUE TITLE
Battery holder backwards in shipped kit

### ISSUE THREAD

**Issue by unwiredben** [hamster/bee-merry#1]
The kit I got from the Tindie store is backwards polarity versus the pictures here, so the positive lead is soldered into the negative hole.  This explains why these pictures have the LEDs pointing the other way too and the sticker on the board indicating the other direction.

**Comment by hamster** [comment]
I updated the paper instructions to follow the sticker but failed to update the GitHub.

I was sent a batch of battery boxes that half had the polarity backwards. To make things work, I put stickers on the boards but obviously I did not call enough attention to the sticker. I'll update the instructions.

**Comment by hamster** [comment]
Updated build instructions to better indicate which way to install them.
